on:
  release:
    types: [published]
  push:
    branches: [ master ]
    tags:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    steps:
    - uses: actions/checkout@v2
      with:
        path: CIL
        fetch-depth: 0
    - name: install cil
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential --fix-missing
        cd CIL
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=install
        sudo cmake --build . --target install
        cd install/lib
        echo "LD_LIBRARY_PATH=$(pwd)" >> $GITHUB_ENV
        cd ../../..
    - name: run multiversion-sphinx
      with:
        run: |
          python -m pip install --upgrade pip
          pip install -U sphinx
          pip install sphinx-multiversion
          pip install -r CIL/docs/source/requirements.txt
          sphinx-multiversion CIL/docs/source CIL/docs/build
    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: CIL/docs/build/
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Download artifact of the html output.
      uses: actions/download-artifact@v2
      with:
        name: DocumentationHTML
        path: docs/build/
    - name: Commit documentation changes
      run: |
        git clone https://github.com/TomographicImaging/CIL.git --branch gh-pages --single-branch gh-pages
        cp -r docs/build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
